// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type TransportType string

const (
	TransportTypeMRT          TransportType = "MRT"
	TransportTypeTransJakarta TransportType = "TransJakarta"
	TransportTypeJakLingko    TransportType = "JakLingko"
)

func (e *TransportType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransportType(s)
	case string:
		*e = TransportType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransportType: %T", src)
	}
	return nil
}

type NullTransportType struct {
	TransportType TransportType
	Valid         bool // Valid is true if TransportType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransportType) Scan(value interface{}) error {
	if value == nil {
		ns.TransportType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransportType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransportType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransportType), nil
}

type Concert struct {
	ID          int32
	VenueID     sql.NullInt32
	Title       string
	EventDate   time.Time
	Description sql.NullString
}

type Hotel struct {
	ID        int32
	Name      string
	Address   string
	Latitude  sql.NullString
	Longitude sql.NullString
	PriceEst  sql.NullString
}

type Itinerary struct {
	ID                 uuid.UUID
	UserID             uuid.NullUUID
	ConcertID          sql.NullInt32
	HotelID            sql.NullInt32
	TransportToVenue   sql.NullInt32
	TransportFromVenue sql.NullInt32
	CreatedAt          sql.NullTime
}

type TransportGeometry struct {
	ID       int32
	RouteID  sql.NullInt32
	PathJson pqtype.NullRawMessage
}

type TransportRoute struct {
	ID            int32
	Mode          TransportType
	RouteName     string
	OriginName    sql.NullString
	DestinationID sql.NullInt32
	EstPrice      sql.NullString
	EstDuration   sql.NullInt32
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	CreatedAt sql.NullTime
}

type Venue struct {
	ID        int32
	Name      string
	Address   string
	Latitude  string
	Longitude string
}
