// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type TransportType string

const (
	TransportTypeMRT          TransportType = "MRT"
	TransportTypeTransJakarta TransportType = "TransJakarta"
	TransportTypeJakLingko    TransportType = "JakLingko"
)

func (e *TransportType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransportType(s)
	case string:
		*e = TransportType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransportType: %T", src)
	}
	return nil
}

type NullTransportType struct {
	TransportType TransportType
	Valid         bool // Valid is true if TransportType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransportType) Scan(value interface{}) error {
	if value == nil {
		ns.TransportType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransportType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransportType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransportType), nil
}

type Concert struct {
	ID          int32
	VenueID     sql.NullInt32
	Title       string
	ArtistName  string
	EventDate   time.Time
	Description sql.NullString
}

type CrowdCheckin struct {
	ID            uuid.UUID
	UserID        uuid.NullUUID
	PickupPointID sql.NullInt32
	CheckInTime   time.Time
}

type Hotel struct {
	ID         int32
	Name       string
	Address    string
	Latitude   string
	Longitude  string
	PriceEst   sql.NullString
	StarRating sql.NullInt32
	Facilities []string
}

type HotelBooking struct {
	ID           int32
	UserID       uuid.NullUUID
	HotelID      sql.NullInt32
	CheckInDate  time.Time
	CheckOutDate time.Time
	Status       string
	CreatedAt    time.Time
}

type IntercityTransport struct {
	ID            int32
	UserID        uuid.NullUUID
	OriginCity    string
	TransportMode string
	DepartureDate time.Time
	ReturnDate    sql.NullTime
	Status        string
	CreatedAt     time.Time
}

type PickupPoint struct {
	ID          int32
	VenueID     sql.NullInt32
	Name        string
	Latitude    string
	Longitude   string
	MaxCapacity int32
}

type Ticket struct {
	ID        int32
	ConcertID sql.NullInt32
	Tier      string
	Price     string
	Stock     int32
}

type TicketOrder struct {
	ID        int32
	UserID    uuid.NullUUID
	TicketID  sql.NullInt32
	Quantity  int32
	Status    string
	CreatedAt time.Time
}

type TransportGeometry struct {
	ID       int32
	RouteID  sql.NullInt32
	PathJson pqtype.NullRawMessage
}

type TransportRoute struct {
	ID            int32
	Mode          TransportType
	RouteName     string
	OriginName    sql.NullString
	DestinationID sql.NullInt32
	EstPrice      sql.NullString
	EstDuration   sql.NullInt32
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	Role      string
	CreatedAt time.Time
}

type Venue struct {
	ID        int32
	Name      string
	Address   string
	Latitude  string
	Longitude string
}
