// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createItinerary = `-- name: CreateItinerary :one

INSERT INTO itineraries (
    user_id, concert_id, hotel_id, transport_to_venue, transport_from_venue
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, created_at
`

type CreateItineraryParams struct {
	UserID             uuid.NullUUID
	ConcertID          sql.NullInt32
	HotelID            sql.NullInt32
	TransportToVenue   sql.NullInt32
	TransportFromVenue sql.NullInt32
}

type CreateItineraryRow struct {
	ID        uuid.UUID
	CreatedAt sql.NullTime
}

// ------------------------------------------ itineraries
// Links the user's choices into a single record.
func (q *Queries) CreateItinerary(ctx context.Context, arg CreateItineraryParams) (CreateItineraryRow, error) {
	row := q.db.QueryRowContext(ctx, createItinerary,
		arg.UserID,
		arg.ConcertID,
		arg.HotelID,
		arg.TransportToVenue,
		arg.TransportFromVenue,
	)
	var i CreateItineraryRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    email, password
) VALUES (
    $1, $2
) RETURNING id, email, created_at
`

type CreateUserParams struct {
	Email    string
	Password string
}

type CreateUserRow struct {
	ID        uuid.UUID
	Email     string
	CreatedAt sql.NullTime
}

// ----------------------------- users
// Used for the registration endpoint.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Password)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const deleteItinerary = `-- name: DeleteItinerary :exec
DELETE FROM itineraries
WHERE id = $1 AND user_id = $2
`

type DeleteItineraryParams struct {
	ID     uuid.UUID
	UserID uuid.NullUUID
}

// Allows users to cancel their plan.
func (q *Queries) DeleteItinerary(ctx context.Context, arg DeleteItineraryParams) error {
	_, err := q.db.ExecContext(ctx, deleteItinerary, arg.ID, arg.UserID)
	return err
}

const getConcert = `-- name: GetConcert :one
SELECT id, venue_id, title, event_date, description 
FROM concerts 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetConcert(ctx context.Context, id int32) (Concert, error) {
	row := q.db.QueryRowContext(ctx, getConcert, id)
	var i Concert
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Title,
		&i.EventDate,
		&i.Description,
	)
	return i, err
}

const getRoutesForVenue = `-- name: GetRoutesForVenue :many
SELECT 
    tr.id, tr.mode, tr.route_name, tr.origin_name, 
    tr.est_price, tr.est_duration, 
    tg.path_json
FROM transport_routes tr
LEFT JOIN transport_geometries tg ON tr.id = tg.route_id
WHERE tr.destination_id = $1
`

type GetRoutesForVenueRow struct {
	ID          int32
	Mode        TransportType
	RouteName   string
	OriginName  sql.NullString
	EstPrice    sql.NullString
	EstDuration sql.NullInt32
	PathJson    pqtype.NullRawMessage
}

// -------------------------------------------- transport routing
// Fetches the "Golden Routes" to a specific venue, including the GeoJSON
func (q *Queries) GetRoutesForVenue(ctx context.Context, destinationID sql.NullInt32) ([]GetRoutesForVenueRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoutesForVenue, destinationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoutesForVenueRow
	for rows.Next() {
		var i GetRoutesForVenueRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.RouteName,
			&i.OriginName,
			&i.EstPrice,
			&i.EstDuration,
			&i.PathJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, created_at 
FROM users 
WHERE email = $1 LIMIT 1
`

// Used to verify credentials during JWT login.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserItineraries = `-- name: GetUserItineraries :many
SELECT 
    i.id AS itinerary_id,
    c.title AS concert_title,
    c.event_date,
    v.name AS venue_name,
    h.name AS hotel_name,
    t_to.mode AS transport_to_mode,
    t_to.route_name AS route_to_venue,
    t_from.mode AS transport_from_mode,
    t_from.route_name AS route_from_venue
FROM itineraries i
JOIN concerts c ON i.concert_id = c.id
JOIN venues v ON c.venue_id = v.id
LEFT JOIN hotels h ON i.hotel_id = h.id
LEFT JOIN transport_routes t_to ON i.transport_to_venue = t_to.id
LEFT JOIN transport_routes t_from ON i.transport_from_venue = t_from.id
WHERE i.user_id = $1
ORDER BY c.event_date ASC
`

type GetUserItinerariesRow struct {
	ItineraryID       uuid.UUID
	ConcertTitle      string
	EventDate         time.Time
	VenueName         string
	HotelName         sql.NullString
	TransportToMode   NullTransportType
	RouteToVenue      sql.NullString
	TransportFromMode NullTransportType
	RouteFromVenue    sql.NullString
}

// The core "All-in-One" query. Joins all related tables to return a complete
// dashboard view of the user's plan.
func (q *Queries) GetUserItineraries(ctx context.Context, userID uuid.NullUUID) ([]GetUserItinerariesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserItineraries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserItinerariesRow
	for rows.Next() {
		var i GetUserItinerariesRow
		if err := rows.Scan(
			&i.ItineraryID,
			&i.ConcertTitle,
			&i.EventDate,
			&i.VenueName,
			&i.HotelName,
			&i.TransportToMode,
			&i.RouteToVenue,
			&i.TransportFromMode,
			&i.RouteFromVenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotels = `-- name: ListHotels :many

SELECT id, name, address, latitude, longitude, price_est 
FROM hotels
`

// ---------------------------------------- hotels
func (q *Queries) ListHotels(ctx context.Context) ([]Hotel, error) {
	rows, err := q.db.QueryContext(ctx, listHotels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hotel
	for rows.Next() {
		var i Hotel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.PriceEst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingConcerts = `-- name: ListUpcomingConcerts :many

SELECT 
    c.id, c.title, c.event_date, c.description, 
    v.id AS venue_id, v.name AS venue_name, v.latitude, v.longitude
FROM concerts c
JOIN venues v ON c.venue_id = v.id
WHERE c.event_date >= NOW()
ORDER BY c.event_date ASC
`

type ListUpcomingConcertsRow struct {
	ID          int32
	Title       string
	EventDate   time.Time
	Description sql.NullString
	VenueID     int32
	VenueName   string
	Latitude    string
	Longitude   string
}

// ---------------------- concert and venues
// Fetches the feed of concerts along with their venue details.
func (q *Queries) ListUpcomingConcerts(ctx context.Context) ([]ListUpcomingConcertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingConcerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingConcertsRow
	for rows.Next() {
		var i ListUpcomingConcertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.EventDate,
			&i.Description,
			&i.VenueID,
			&i.VenueName,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
