// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const createCrowdCheckin = `-- name: CreateCrowdCheckin :one
INSERT INTO crowd_checkins (
    user_id, pickup_point_id
) VALUES (
    $1, $2
) RETURNING id, check_in_time
`

type CreateCrowdCheckinParams struct {
	UserID        uuid.NullUUID
	PickupPointID sql.NullInt32
}

type CreateCrowdCheckinRow struct {
	ID          uuid.UUID
	CheckInTime time.Time
}

// NEW: Logs a user checking into a pickup point.
func (q *Queries) CreateCrowdCheckin(ctx context.Context, arg CreateCrowdCheckinParams) (CreateCrowdCheckinRow, error) {
	row := q.db.QueryRowContext(ctx, createCrowdCheckin, arg.UserID, arg.PickupPointID)
	var i CreateCrowdCheckinRow
	err := row.Scan(&i.ID, &i.CheckInTime)
	return i, err
}

const createItinerary = `-- name: CreateItinerary :one

INSERT INTO itineraries (
    user_id, ticket_id, hotel_id, hotel_check_in, hotel_check_out, 
    transport_to_venue, transport_from_venue, out_of_town_transport
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, created_at
`

type CreateItineraryParams struct {
	UserID             uuid.NullUUID
	TicketID           sql.NullInt32
	HotelID            sql.NullInt32
	HotelCheckIn       sql.NullTime
	HotelCheckOut      sql.NullTime
	TransportToVenue   sql.NullInt32
	TransportFromVenue sql.NullInt32
	OutOfTownTransport pqtype.NullRawMessage
}

type CreateItineraryRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
}

// --------------------- ITINERARIES & DASHBOARD (FR-07) -----------------------
// Updated to accept ticket_id, check-in/out dates, and out_of_town JSON transport data.
func (q *Queries) CreateItinerary(ctx context.Context, arg CreateItineraryParams) (CreateItineraryRow, error) {
	row := q.db.QueryRowContext(ctx, createItinerary,
		arg.UserID,
		arg.TicketID,
		arg.HotelID,
		arg.HotelCheckIn,
		arg.HotelCheckOut,
		arg.TransportToVenue,
		arg.TransportFromVenue,
		arg.OutOfTownTransport,
	)
	var i CreateItineraryRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    email, password, role
) VALUES (
    $1, $2, $3
) RETURNING id, email, role, created_at
`

type CreateUserParams struct {
	Email    string
	Password string
	Role     string
}

type CreateUserRow struct {
	ID        uuid.UUID
	Email     string
	Role      string
	CreatedAt time.Time
}

// ----------------------------- USERS (FR-01) -------------------------------
// Used for the registration endpoint. Now returns the 'role'.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Password, arg.Role)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteItinerary = `-- name: DeleteItinerary :exec
DELETE FROM itineraries
WHERE id = $1 AND user_id = $2
`

type DeleteItineraryParams struct {
	ID     uuid.UUID
	UserID uuid.NullUUID
}

// Allows users to cancel their plan.
func (q *Queries) DeleteItinerary(ctx context.Context, arg DeleteItineraryParams) error {
	_, err := q.db.ExecContext(ctx, deleteItinerary, arg.ID, arg.UserID)
	return err
}

const getConcert = `-- name: GetConcert :one
SELECT id, venue_id, title, artist_name, event_date, description 
FROM concerts 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetConcert(ctx context.Context, id int32) (Concert, error) {
	row := q.db.QueryRowContext(ctx, getConcert, id)
	var i Concert
	err := row.Scan(
		&i.ID,
		&i.VenueID,
		&i.Title,
		&i.ArtistName,
		&i.EventDate,
		&i.Description,
	)
	return i, err
}

const getRoutesForVenue = `-- name: GetRoutesForVenue :many

SELECT 
    tr.id, tr.mode, tr.route_name, tr.origin_name, 
    tr.est_price, tr.est_duration, 
    tg.path_json
FROM transport_routes tr
LEFT JOIN transport_geometries tg ON tr.id = tg.route_id
WHERE tr.destination_id = $1
`

type GetRoutesForVenueRow struct {
	ID          int32
	Mode        TransportType
	RouteName   string
	OriginName  sql.NullString
	EstPrice    sql.NullString
	EstDuration sql.NullInt32
	PathJson    pqtype.NullRawMessage
}

// ---------------------- TRANSPORT ROUTING (FR-05) ------------------------
// Fetches the "Golden Routes" to a specific venue, including the GeoJSON.
func (q *Queries) GetRoutesForVenue(ctx context.Context, destinationID sql.NullInt32) ([]GetRoutesForVenueRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoutesForVenue, destinationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoutesForVenueRow
	for rows.Next() {
		var i GetRoutesForVenueRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.RouteName,
			&i.OriginName,
			&i.EstPrice,
			&i.EstDuration,
			&i.PathJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketsForConcert = `-- name: GetTicketsForConcert :many
SELECT id, concert_id, tier, price, stock 
FROM tickets 
WHERE concert_id = $1 
ORDER BY price ASC
`

// NEW: Fetches available ticket tiers and stock for a specific concert.
func (q *Queries) GetTicketsForConcert(ctx context.Context, concertID sql.NullInt32) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, getTicketsForConcert, concertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.ConcertID,
			&i.Tier,
			&i.Price,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, role, created_at 
FROM users 
WHERE email = $1 LIMIT 1
`

// Used to verify credentials during JWT login. Now fetches 'role' for the payload.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserItineraries = `-- name: GetUserItineraries :many
SELECT 
    i.id AS itinerary_id,
    c.title AS concert_title,
    c.artist_name,
    c.event_date,
    v.name AS venue_name,
    t.tier AS ticket_tier,
    h.name AS hotel_name,
    i.hotel_check_in,
    i.hotel_check_out,
    t_to.mode AS transport_to_mode,
    t_to.route_name AS route_to_venue,
    t_from.mode AS transport_from_mode,
    t_from.route_name AS route_from_venue,
    i.out_of_town_transport
FROM itineraries i
JOIN tickets t ON i.ticket_id = t.id
JOIN concerts c ON t.concert_id = c.id
JOIN venues v ON c.venue_id = v.id
LEFT JOIN hotels h ON i.hotel_id = h.id
LEFT JOIN transport_routes t_to ON i.transport_to_venue = t_to.id
LEFT JOIN transport_routes t_from ON i.transport_from_venue = t_from.id
WHERE i.user_id = $1
ORDER BY c.event_date ASC
`

type GetUserItinerariesRow struct {
	ItineraryID        uuid.UUID
	ConcertTitle       string
	ArtistName         string
	EventDate          time.Time
	VenueName          string
	TicketTier         string
	HotelName          sql.NullString
	HotelCheckIn       sql.NullTime
	HotelCheckOut      sql.NullTime
	TransportToMode    NullTransportType
	RouteToVenue       sql.NullString
	TransportFromMode  NullTransportType
	RouteFromVenue     sql.NullString
	OutOfTownTransport pqtype.NullRawMessage
}

// The core "All-in-One" query. Completely overhauled to link tickets, dates, and JSON data.
func (q *Queries) GetUserItineraries(ctx context.Context, userID uuid.NullUUID) ([]GetUserItinerariesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserItineraries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserItinerariesRow
	for rows.Next() {
		var i GetUserItinerariesRow
		if err := rows.Scan(
			&i.ItineraryID,
			&i.ConcertTitle,
			&i.ArtistName,
			&i.EventDate,
			&i.VenueName,
			&i.TicketTier,
			&i.HotelName,
			&i.HotelCheckIn,
			&i.HotelCheckOut,
			&i.TransportToMode,
			&i.RouteToVenue,
			&i.TransportFromMode,
			&i.RouteFromVenue,
			&i.OutOfTownTransport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHotels = `-- name: ListHotels :many

SELECT id, name, address, latitude, longitude, price_est, star_rating, facilities 
FROM hotels
`

// ------------------------------ HOTELS (FR-03) --------------------------------
// Updated to pull the new star_rating and facilities fields.
func (q *Queries) ListHotels(ctx context.Context) ([]Hotel, error) {
	rows, err := q.db.QueryContext(ctx, listHotels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hotel
	for rows.Next() {
		var i Hotel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.PriceEst,
			&i.StarRating,
			pq.Array(&i.Facilities),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPickupPointsForVenue = `-- name: ListPickupPointsForVenue :many

SELECT 
    p.id, p.name, p.latitude, p.longitude, p.max_capacity,
    (SELECT COUNT(id) FROM crowd_checkins WHERE pickup_point_id = p.id) AS current_count
FROM pickup_points p
WHERE p.venue_id = $1
`

type ListPickupPointsForVenueRow struct {
	ID           int32
	Name         string
	Latitude     string
	Longitude    string
	MaxCapacity  int32
	CurrentCount int64
}

// -------------- CROWD TRACKING & PICKUP POINTS (FR-06) ----------------
// NEW: Lists pickup points and calculates their current check-in count dynamically.
func (q *Queries) ListPickupPointsForVenue(ctx context.Context, venueID sql.NullInt32) ([]ListPickupPointsForVenueRow, error) {
	rows, err := q.db.QueryContext(ctx, listPickupPointsForVenue, venueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPickupPointsForVenueRow
	for rows.Next() {
		var i ListPickupPointsForVenueRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Latitude,
			&i.Longitude,
			&i.MaxCapacity,
			&i.CurrentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingConcerts = `-- name: ListUpcomingConcerts :many

SELECT 
    c.id, c.title, c.artist_name, c.event_date, c.description, 
    v.id AS venue_id, v.name AS venue_name, v.latitude, v.longitude
FROM concerts c
JOIN venues v ON c.venue_id = v.id
WHERE c.event_date >= NOW()
ORDER BY c.event_date ASC
`

type ListUpcomingConcertsRow struct {
	ID          int32
	Title       string
	ArtistName  string
	EventDate   time.Time
	Description sql.NullString
	VenueID     int32
	VenueName   string
	Latitude    string
	Longitude   string
}

// ---------------------- CONCERTS & TICKETS (FR-02) ------------------------
// Fetches the feed of concerts. Updated to include artist_name.
func (q *Queries) ListUpcomingConcerts(ctx context.Context) ([]ListUpcomingConcertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingConcerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingConcertsRow
	for rows.Next() {
		var i ListUpcomingConcertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistName,
			&i.EventDate,
			&i.Description,
			&i.VenueID,
			&i.VenueName,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketStock = `-- name: UpdateTicketStock :one
UPDATE tickets 
SET stock = stock - $2 
WHERE id = $1 AND stock >= $2 
RETURNING id, stock
`

type UpdateTicketStockParams struct {
	ID    int32
	Stock int32
}

type UpdateTicketStockRow struct {
	ID    int32
	Stock int32
}

// NEW: Safely decrements stock during booking to handle the 'Sold Out' requirement.
func (q *Queries) UpdateTicketStock(ctx context.Context, arg UpdateTicketStockParams) (UpdateTicketStockRow, error) {
	row := q.db.QueryRowContext(ctx, updateTicketStock, arg.ID, arg.Stock)
	var i UpdateTicketStockRow
	err := row.Scan(&i.ID, &i.Stock)
	return i, err
}
